# Generated by Django 2.2.1 on 2020-05-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=10)),
                ('team_logo', models.ImageField(blank=True, upload_to='team_logo')),
            ],
        ),
    ]
